name: zovcord
description: "A new Flutter project."

publish_to: 'none' 


version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  shared_preferences: ^2.3.3
  go_router: ^14.6.2
  provider: ^6.1.2
  get_it: ^8.0.2
  emoji_picker_flutter: ^3.1.0
  intl: ^0.18.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
 
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/pic/flag.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
